export const MoviesActions = {
    LOAD_LATEST_MOVIES_ACTION: 'LOAD_LATEST_MOVIES_ACTION',
    LOAD_LATEST_MOVIES: 'LOAD_LATEST_MOVIES',
    LOAD_MOVIE_DETAILS_ACTION: 'LOAD_MOVIE_DETAILS_ACTION',
    LOAD_MOVIE_DETAILS: 'LOAD_MOVIE_DETAILS'
}

export const PersonsActions = {
    LOAD_MOVIE_CNC_ACTION: 'LOAD_MOVIE_CNC_ACTION',
    LOAD_MOVIE_CNC: 'LOAD_MOVIE_CNC'
}